language: cpp
compiler:
    - gcc
# install additional packages
# http://docs.travis-ci.com/user/installing-dependencies/
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libboost-dev
script:
    - make -f Makefile.cvs
    - cd build
    - make -j 4
    - sudo make install

