#
# Makefile.cvs
#

# enable coverage if $COVERAGE is set to 1
ifeq ($(COVERAGE), 1)
EXTRA_PARAMS := -DENABLE_CODE_COVERAGE=ON
endif

all: configure

configure: clean
	./bootstrap.sh ; \
	mkdir build ; \
	cd build ; \
	cmake .. \
	-DCMAKE_BUILD_TYPE=RELEASE $(EXTRA_PARAMS)

install: configure
	cd build ; \
	make && make install

reconf:
	cd build ; \
	cmake rebuild_cache

clean:
	rm -rf build \
		CMakeLists.txt
