#
# Makefile.repo
#


all: build

build: configure
	cd build; \
	make -j 8

configure: clean
	mkdir build; \
	cd build; \
	cmake ..

install: configure
	cd build; \
	make && make install

reconf:
	cd build; \
	cmake rebuild_cache

clean:
	rm -rf build
